// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"ordersystem/ent/inventory"
	"ordersystem/ent/order"
	"ordersystem/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InventoryQuery is the builder for querying Inventory entities.
type InventoryQuery struct {
	config
	ctx        *QueryContext
	order      []inventory.OrderOption
	inters     []Interceptor
	predicates []predicate.Inventory
	withOrder  *OrderQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InventoryQuery builder.
func (iq *InventoryQuery) Where(ps ...predicate.Inventory) *InventoryQuery {
	iq.predicates = append(iq.predicates, ps...)
	return iq
}

// Limit the number of records to be returned by this query.
func (iq *InventoryQuery) Limit(limit int) *InventoryQuery {
	iq.ctx.Limit = &limit
	return iq
}

// Offset to start from.
func (iq *InventoryQuery) Offset(offset int) *InventoryQuery {
	iq.ctx.Offset = &offset
	return iq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iq *InventoryQuery) Unique(unique bool) *InventoryQuery {
	iq.ctx.Unique = &unique
	return iq
}

// Order specifies how the records should be ordered.
func (iq *InventoryQuery) Order(o ...inventory.OrderOption) *InventoryQuery {
	iq.order = append(iq.order, o...)
	return iq
}

// QueryOrder chains the current query on the "order" edge.
func (iq *InventoryQuery) QueryOrder() *OrderQuery {
	query := (&OrderClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(inventory.Table, inventory.FieldID, selector),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, inventory.OrderTable, inventory.OrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Inventory entity from the query.
// Returns a *NotFoundError when no Inventory was found.
func (iq *InventoryQuery) First(ctx context.Context) (*Inventory, error) {
	nodes, err := iq.Limit(1).All(setContextOp(ctx, iq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{inventory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iq *InventoryQuery) FirstX(ctx context.Context) *Inventory {
	node, err := iq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Inventory ID from the query.
// Returns a *NotFoundError when no Inventory ID was found.
func (iq *InventoryQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = iq.Limit(1).IDs(setContextOp(ctx, iq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{inventory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iq *InventoryQuery) FirstIDX(ctx context.Context) int64 {
	id, err := iq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Inventory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Inventory entity is found.
// Returns a *NotFoundError when no Inventory entities are found.
func (iq *InventoryQuery) Only(ctx context.Context) (*Inventory, error) {
	nodes, err := iq.Limit(2).All(setContextOp(ctx, iq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{inventory.Label}
	default:
		return nil, &NotSingularError{inventory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iq *InventoryQuery) OnlyX(ctx context.Context) *Inventory {
	node, err := iq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Inventory ID in the query.
// Returns a *NotSingularError when more than one Inventory ID is found.
// Returns a *NotFoundError when no entities are found.
func (iq *InventoryQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = iq.Limit(2).IDs(setContextOp(ctx, iq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{inventory.Label}
	default:
		err = &NotSingularError{inventory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iq *InventoryQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := iq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Inventories.
func (iq *InventoryQuery) All(ctx context.Context) ([]*Inventory, error) {
	ctx = setContextOp(ctx, iq.ctx, "All")
	if err := iq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Inventory, *InventoryQuery]()
	return withInterceptors[[]*Inventory](ctx, iq, qr, iq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iq *InventoryQuery) AllX(ctx context.Context) []*Inventory {
	nodes, err := iq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Inventory IDs.
func (iq *InventoryQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if iq.ctx.Unique == nil && iq.path != nil {
		iq.Unique(true)
	}
	ctx = setContextOp(ctx, iq.ctx, "IDs")
	if err = iq.Select(inventory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iq *InventoryQuery) IDsX(ctx context.Context) []int64 {
	ids, err := iq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iq *InventoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iq.ctx, "Count")
	if err := iq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iq, querierCount[*InventoryQuery](), iq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iq *InventoryQuery) CountX(ctx context.Context) int {
	count, err := iq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iq *InventoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iq.ctx, "Exist")
	switch _, err := iq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iq *InventoryQuery) ExistX(ctx context.Context) bool {
	exist, err := iq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InventoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iq *InventoryQuery) Clone() *InventoryQuery {
	if iq == nil {
		return nil
	}
	return &InventoryQuery{
		config:     iq.config,
		ctx:        iq.ctx.Clone(),
		order:      append([]inventory.OrderOption{}, iq.order...),
		inters:     append([]Interceptor{}, iq.inters...),
		predicates: append([]predicate.Inventory{}, iq.predicates...),
		withOrder:  iq.withOrder.Clone(),
		// clone intermediate query.
		sql:  iq.sql.Clone(),
		path: iq.path,
	}
}

// WithOrder tells the query-builder to eager-load the nodes that are connected to
// the "order" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InventoryQuery) WithOrder(opts ...func(*OrderQuery)) *InventoryQuery {
	query := (&OrderClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withOrder = query
	return iq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Inventory.Query().
//		GroupBy(inventory.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iq *InventoryQuery) GroupBy(field string, fields ...string) *InventoryGroupBy {
	iq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InventoryGroupBy{build: iq}
	grbuild.flds = &iq.ctx.Fields
	grbuild.label = inventory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Inventory.Query().
//		Select(inventory.FieldCreateTime).
//		Scan(ctx, &v)
func (iq *InventoryQuery) Select(fields ...string) *InventorySelect {
	iq.ctx.Fields = append(iq.ctx.Fields, fields...)
	sbuild := &InventorySelect{InventoryQuery: iq}
	sbuild.label = inventory.Label
	sbuild.flds, sbuild.scan = &iq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InventorySelect configured with the given aggregations.
func (iq *InventoryQuery) Aggregate(fns ...AggregateFunc) *InventorySelect {
	return iq.Select().Aggregate(fns...)
}

func (iq *InventoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iq); err != nil {
				return err
			}
		}
	}
	for _, f := range iq.ctx.Fields {
		if !inventory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iq.path != nil {
		prev, err := iq.path(ctx)
		if err != nil {
			return err
		}
		iq.sql = prev
	}
	return nil
}

func (iq *InventoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Inventory, error) {
	var (
		nodes       = []*Inventory{}
		_spec       = iq.querySpec()
		loadedTypes = [1]bool{
			iq.withOrder != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Inventory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Inventory{config: iq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := iq.withOrder; query != nil {
		if err := iq.loadOrder(ctx, query, nodes,
			func(n *Inventory) { n.Edges.Order = []*Order{} },
			func(n *Inventory, e *Order) { n.Edges.Order = append(n.Edges.Order, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (iq *InventoryQuery) loadOrder(ctx context.Context, query *OrderQuery, nodes []*Inventory, init func(*Inventory), assign func(*Inventory, *Order)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Inventory)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(order.FieldInventoryID)
	}
	query.Where(predicate.Order(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(inventory.OrderColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.InventoryID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "inventory_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (iq *InventoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iq.querySpec()
	_spec.Node.Columns = iq.ctx.Fields
	if len(iq.ctx.Fields) > 0 {
		_spec.Unique = iq.ctx.Unique != nil && *iq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iq.driver, _spec)
}

func (iq *InventoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(inventory.Table, inventory.Columns, sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64))
	_spec.From = iq.sql
	if unique := iq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iq.path != nil {
		_spec.Unique = true
	}
	if fields := iq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inventory.FieldID)
		for i := range fields {
			if fields[i] != inventory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iq *InventoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iq.driver.Dialect())
	t1 := builder.Table(inventory.Table)
	columns := iq.ctx.Fields
	if len(columns) == 0 {
		columns = inventory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iq.sql != nil {
		selector = iq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iq.ctx.Unique != nil && *iq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range iq.predicates {
		p(selector)
	}
	for _, p := range iq.order {
		p(selector)
	}
	if offset := iq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InventoryGroupBy is the group-by builder for Inventory entities.
type InventoryGroupBy struct {
	selector
	build *InventoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (igb *InventoryGroupBy) Aggregate(fns ...AggregateFunc) *InventoryGroupBy {
	igb.fns = append(igb.fns, fns...)
	return igb
}

// Scan applies the selector query and scans the result into the given value.
func (igb *InventoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, igb.build.ctx, "GroupBy")
	if err := igb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InventoryQuery, *InventoryGroupBy](ctx, igb.build, igb, igb.build.inters, v)
}

func (igb *InventoryGroupBy) sqlScan(ctx context.Context, root *InventoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(igb.fns))
	for _, fn := range igb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*igb.flds)+len(igb.fns))
		for _, f := range *igb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*igb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := igb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InventorySelect is the builder for selecting fields of Inventory entities.
type InventorySelect struct {
	*InventoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *InventorySelect) Aggregate(fns ...AggregateFunc) *InventorySelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *InventorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, is.ctx, "Select")
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InventoryQuery, *InventorySelect](ctx, is.InventoryQuery, is, is.inters, v)
}

func (is *InventorySelect) sqlScan(ctx context.Context, root *InventoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
