// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ordersystem/ent/inventory"
	"ordersystem/ent/order"
	"ordersystem/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (ou *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetUpdateTime sets the "update_time" field.
func (ou *OrderUpdate) SetUpdateTime(t time.Time) *OrderUpdate {
	ou.mutation.SetUpdateTime(t)
	return ou
}

// SetName sets the "name" field.
func (ou *OrderUpdate) SetName(s string) *OrderUpdate {
	ou.mutation.SetName(s)
	return ou
}

// SetInventoryID sets the "inventory_id" field.
func (ou *OrderUpdate) SetInventoryID(i int64) *OrderUpdate {
	ou.mutation.SetInventoryID(i)
	return ou
}

// SetNillableInventoryID sets the "inventory_id" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableInventoryID(i *int64) *OrderUpdate {
	if i != nil {
		ou.SetInventoryID(*i)
	}
	return ou
}

// ClearInventoryID clears the value of the "inventory_id" field.
func (ou *OrderUpdate) ClearInventoryID() *OrderUpdate {
	ou.mutation.ClearInventoryID()
	return ou
}

// SetCount sets the "count" field.
func (ou *OrderUpdate) SetCount(i int) *OrderUpdate {
	ou.mutation.ResetCount()
	ou.mutation.SetCount(i)
	return ou
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableCount(i *int) *OrderUpdate {
	if i != nil {
		ou.SetCount(*i)
	}
	return ou
}

// AddCount adds i to the "count" field.
func (ou *OrderUpdate) AddCount(i int) *OrderUpdate {
	ou.mutation.AddCount(i)
	return ou
}

// SetStatus sets the "status" field.
func (ou *OrderUpdate) SetStatus(i int) *OrderUpdate {
	ou.mutation.ResetStatus()
	ou.mutation.SetStatus(i)
	return ou
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableStatus(i *int) *OrderUpdate {
	if i != nil {
		ou.SetStatus(*i)
	}
	return ou
}

// AddStatus adds i to the "status" field.
func (ou *OrderUpdate) AddStatus(i int) *OrderUpdate {
	ou.mutation.AddStatus(i)
	return ou
}

// SetInventory sets the "inventory" edge to the Inventory entity.
func (ou *OrderUpdate) SetInventory(i *Inventory) *OrderUpdate {
	return ou.SetInventoryID(i.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (ou *OrderUpdate) Mutation() *OrderMutation {
	return ou.mutation
}

// ClearInventory clears the "inventory" edge to the Inventory entity.
func (ou *OrderUpdate) ClearInventory() *OrderUpdate {
	ou.mutation.ClearInventory()
	return ou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrderUpdate) Save(ctx context.Context) (int, error) {
	ou.defaults()
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrderUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrderUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OrderUpdate) defaults() {
	if _, ok := ou.mutation.UpdateTime(); !ok {
		v := order.UpdateDefaultUpdateTime()
		ou.mutation.SetUpdateTime(v)
	}
}

func (ou *OrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.UpdateTime(); ok {
		_spec.SetField(order.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := ou.mutation.Name(); ok {
		_spec.SetField(order.FieldName, field.TypeString, value)
	}
	if value, ok := ou.mutation.Count(); ok {
		_spec.SetField(order.FieldCount, field.TypeInt, value)
	}
	if value, ok := ou.mutation.AddedCount(); ok {
		_spec.AddField(order.FieldCount, field.TypeInt, value)
	}
	if value, ok := ou.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeInt, value)
	}
	if value, ok := ou.mutation.AddedStatus(); ok {
		_spec.AddField(order.FieldStatus, field.TypeInt, value)
	}
	if ou.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.InventoryTable,
			Columns: []string{order.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.InventoryTable,
			Columns: []string{order.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetUpdateTime sets the "update_time" field.
func (ouo *OrderUpdateOne) SetUpdateTime(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetUpdateTime(t)
	return ouo
}

// SetName sets the "name" field.
func (ouo *OrderUpdateOne) SetName(s string) *OrderUpdateOne {
	ouo.mutation.SetName(s)
	return ouo
}

// SetInventoryID sets the "inventory_id" field.
func (ouo *OrderUpdateOne) SetInventoryID(i int64) *OrderUpdateOne {
	ouo.mutation.SetInventoryID(i)
	return ouo
}

// SetNillableInventoryID sets the "inventory_id" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableInventoryID(i *int64) *OrderUpdateOne {
	if i != nil {
		ouo.SetInventoryID(*i)
	}
	return ouo
}

// ClearInventoryID clears the value of the "inventory_id" field.
func (ouo *OrderUpdateOne) ClearInventoryID() *OrderUpdateOne {
	ouo.mutation.ClearInventoryID()
	return ouo
}

// SetCount sets the "count" field.
func (ouo *OrderUpdateOne) SetCount(i int) *OrderUpdateOne {
	ouo.mutation.ResetCount()
	ouo.mutation.SetCount(i)
	return ouo
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableCount(i *int) *OrderUpdateOne {
	if i != nil {
		ouo.SetCount(*i)
	}
	return ouo
}

// AddCount adds i to the "count" field.
func (ouo *OrderUpdateOne) AddCount(i int) *OrderUpdateOne {
	ouo.mutation.AddCount(i)
	return ouo
}

// SetStatus sets the "status" field.
func (ouo *OrderUpdateOne) SetStatus(i int) *OrderUpdateOne {
	ouo.mutation.ResetStatus()
	ouo.mutation.SetStatus(i)
	return ouo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableStatus(i *int) *OrderUpdateOne {
	if i != nil {
		ouo.SetStatus(*i)
	}
	return ouo
}

// AddStatus adds i to the "status" field.
func (ouo *OrderUpdateOne) AddStatus(i int) *OrderUpdateOne {
	ouo.mutation.AddStatus(i)
	return ouo
}

// SetInventory sets the "inventory" edge to the Inventory entity.
func (ouo *OrderUpdateOne) SetInventory(i *Inventory) *OrderUpdateOne {
	return ouo.SetInventoryID(i.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (ouo *OrderUpdateOne) Mutation() *OrderMutation {
	return ouo.mutation
}

// ClearInventory clears the "inventory" edge to the Inventory entity.
func (ouo *OrderUpdateOne) ClearInventory() *OrderUpdateOne {
	ouo.mutation.ClearInventory()
	return ouo
}

// Where appends a list predicates to the OrderUpdate builder.
func (ouo *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Order entity.
func (ouo *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	ouo.defaults()
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OrderUpdateOne) defaults() {
	if _, ok := ouo.mutation.UpdateTime(); !ok {
		v := order.UpdateDefaultUpdateTime()
		ouo.mutation.SetUpdateTime(v)
	}
}

func (ouo *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.UpdateTime(); ok {
		_spec.SetField(order.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.Name(); ok {
		_spec.SetField(order.FieldName, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Count(); ok {
		_spec.SetField(order.FieldCount, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.AddedCount(); ok {
		_spec.AddField(order.FieldCount, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.AddedStatus(); ok {
		_spec.AddField(order.FieldStatus, field.TypeInt, value)
	}
	if ouo.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.InventoryTable,
			Columns: []string{order.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.InventoryTable,
			Columns: []string{order.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
